<!DOCTYPE html>
<html>
<head>
<title>10543033</title>
</head>
<body>
<p>hello world. today is 2020.05.06.</p>
<a href="test2.html">This is my test1.</a>
<iframe width="560" height="315" src="https://www.youtube.com/embed/8tuzFSXeKI0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</body>
</html>
<TABLE border=1 bordercolor=800000 width=100%>

<TR>
<TD width=50>第１列，第１格</TD>
<TD width=100>第１列，第２格</TD>
<TD>第１列，第３格</TD>
</TR>

<TR>
<TD width=50>第２列，第１格</TD>
<TD width=100>第２列，第２格</TD>
<TD>第２列，第３格</TD>
</TR>

</TABLE>
